# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew clean build jacocoTestReport sonarqube -info -Dsonar.organization=$SONAR_ORGANIZATION -Dsonar.host.url=$SONAR_HOST_URL -Dsonar.login=$SONAR_LOGIN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACTORY_USERNAME: apptastic
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          BINTRAY_USER: apptastic
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          GRGIT_USER: ${{ secrets.GRGIT_USER }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_ORGANIZATION: w3stling-github
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
      - name: Publish build
        run: ./gradlew gitPublishPush bintrayUpload
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ARTIFACTORY_USERNAME: apptastic
          ARTIFACTORY_PASSWORD: ${{ secrets.ARTIFACTORY_PASSWORD }}
          BINTRAY_USER: apptastic
          BINTRAY_KEY: ${{ secrets.BINTRAY_KEY }}
          GRGIT_USER: ${{ secrets.GRGIT_USER }}
          SONAR_HOST_URL: https://sonarcloud.io
          SONAR_ORGANIZATION: w3stling-github
          SONAR_LOGIN: ${{ secrets.SONAR_LOGIN }}
