name: 'Test Report'
on:
  workflow_run:
    workflows: ['Pull Request Check']      # runs after CI workflow
    types:
      - completed
jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - uses: dorny/test-reporter@v1
        with:
          artifact: test-results                       # artifact name
          name: Tests 🧪                               # Name of the check run which will be created
          path: './**/build/test-results/test/*.xml'   # Path to test results (inside artifact .zip)
          reporter: java-junit                         # Format of test results